# Generated by Django 5.0 on 2024-06-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="total_score",
            field=models.IntegerField(default=0, verbose_name="Total Score"),
        ),
    ]
