# Generated by Django 5.0 on 2024-07-17 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('workout_type', models.CharField(choices=[('Leg Day', 'Leg Day'), ('Chest/Shoulders/Triceps', 'Chest/Shoulders/Triceps'), ('Back/Biceps', 'Back/Biceps'), ('Core/Other', 'Core/Other')], default='Core/Other', max_length=50)),
                ('primary_muscle', models.CharField(max_length=100)),
                ('secondary_muscle', models.CharField(blank=True, max_length=100)),
                ('additional_muscles', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('weight', models.FloatField()),
                ('unit', models.CharField(max_length=10)),
                ('reps', models.IntegerField()),
                ('sets', models.IntegerField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise')),
            ],
        ),
    ]
